spring:
  application:
    name: poc-1-kafka-consumer-ms-springboot

server:
  port: 8082

config:
  kafka:
    bootstrap-server-config: "localhost:29092"
    topics:
      poc-1-messages: 'poc-1-messages'
